"""empty message

Revision ID: 2ae0c688946
Revises: a0c47a7848
Create Date: 2014-09-22 19:30:04.716020

"""

# revision identifiers, used by Alembic.
revision = '2ae0c688946'
down_revision = 'a0c47a7848'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('priority', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'priority')
    ### end Alembic commands ###
