"""empty message

Revision ID: 30c5ec2dce4d
Revises: 523b172372ae
Create Date: 2015-06-03 00:54:55.961511

"""

# revision identifiers, used by Alembic.
revision = '30c5ec2dce4d'
down_revision = '523b172372ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
